/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sung' at '17. 5. 28 오후 10:52' with Gradle 2.14.1
 *
 * @author sung, @date 17. 5. 28 오후 10:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
